version: '3'

services:
  app1:
    container_name: fastapi_code_deploy
    image: fastapi_code_deploy
    restart: always
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
    volumes:
      - ./:/FastAPI
    working_dir: /FastAPI
    network_mode: "host"
    # entrypoint: /bin/sh
    # tty: true
    # stdin_open: true
    command: uvicorn main:app --reload --host=0.0.0.0 --port=10001 --workers=2
    # command: uvicorn main:app --host=0.0.0.0 --port=10001 --workers=2

  # app2:
  #   container_name: fastapi_test
  #   image: fastapi_test
  #   #restart: always
  #   build: 
  #     context: ./docker
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9000:8000"
  #   volumes:
  #     - ./:/FastAPI
  #   working_dir: /FastAPI
  #   # network_mode: "host"
  #   # entrypoint: /bin/sh
  #   # tty: true
  #   # stdin_open: true
  #   command: uvicorn main:app --reload --host=0.0.0.0 --port=8000

    
  
