version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_container
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    # environment:
    #   - DB_URL=postgresql://${PG_USER}:${PG_PASSWORD}@postgres:${PG_PORT}/${PG_DB}
    #   - SCRIPT_DB_URL=postgresql://${PG_USER}:${PG_PASSWORD}@localhost:${PG_PORT}/${PG_DB}
    # depends_on:
    #   - postgres

#   postgres:
#     build:
#       context: ./
#       dockerfile: Dockerfile.pg
#     container_name: postgres_container
#     restart: always
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=${PG_USER}
#       - POSTGRES_PASSWORD=${PG_PASSWORD}

volumes:
  db_data: {}
