version: '3'

services:
  app:
    container_name: fastapi_test
    image: fastapi_test
    #restart: always
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/FastAPI
    working_dir: /FastAPI
    network_mode: "host"
    # entrypoint: /bin/sh
    # tty: true
    # stdin_open: true
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8000
  
