version: '3'

services:
    fastapi:
        container_name: fastapi
        image: fastapi
        environment:
            - TZ=Asia/Seoul
        restart: always
        build: 
            context: ./docker
            dockerfile: Dockerfile
        volumes:
        - ./:/FastAPI
        working_dir: /FastAPI
        network_mode: "host"
        # entrypoint: /bin/sh
        # tty: true
        # stdin_open: true
        command: uvicorn main:app --reload --host=0.0.0.0 --port=12345 --workers=1
        # command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10001
